#pragma once

#define NYUSH_VTS_ESCAPE "\x1b"

#define NYUSH_VTS_SAVE_CURSOR NYUSH_VTS_ESCAPE "7"
#define NYUSH_VTS_RESTORE_CURSOR NYUSH_VTS_ESCAPE "8"

#define __NYUSH_VTS_TEXT_FORMATTING(VALUE) NYUSH_VTS_ESCAPE "[" #VALUE "m"

#define NYUSH_VTS_SET_DEFAULT __NYUSH_VTS_TEXT_FORMATTING(0)

#define NYUSH_VTS_ADD_BOLD __NYUSH_VTS_TEXT_FORMATTING(1)
#define NYUSH_VTS_REMOVE_BOLD __NYUSH_VTS_TEXT_FORMATTING(22)

#define NYUSH_VTS_ADD_UNDERLINE __NYUSH_VTS_TEXT_FORMATTING(4)
#define NYUSH_VTS_REMOVE_UNDERLINE __NYUSH_VTS_TEXT_FORMATTING(24)

#define NYUSH_VTS_NEGATIVE __NYUSH_VTS_TEXT_FORMATTING(7)
#define NYUSH_VTS_POSITIVE __NYUSH_VTS_TEXT_FORMATTING(27)

#define NYUSH_VTS_FOREGROUND_BLACK __NYUSH_VTS_TEXT_FORMATTING(30)
#define NYUSH_VTS_FOREGROUND_RED __NYUSH_VTS_TEXT_FORMATTING(31)
#define NYUSH_VTS_FOREGROUND_GREEN __NYUSH_VTS_TEXT_FORMATTING(32)
#define NYUSH_VTS_FOREGROUND_YELLOW __NYUSH_VTS_TEXT_FORMATTING(33)
#define NYUSH_VTS_FOREGROUND_BLUE __NYUSH_VTS_TEXT_FORMATTING(34)
#define NYUSH_VTS_FOREGROUND_MAGENTA __NYUSH_VTS_TEXT_FORMATTING(35)
#define NYUSH_VTS_FOREGROUND_CYAN __NYUSH_VTS_TEXT_FORMATTING(36)
#define NYUSH_VTS_FOREGROUND_WHITE __NYUSH_VTS_TEXT_FORMATTING(37)
#define NYUSH_VTS_FOREGROUND_BRIGHT_BLACK __NYUSH_VTS_TEXT_FORMATTING(90)
#define NYUSH_VTS_FOREGROUND_BRIGHT_RED __NYUSH_VTS_TEXT_FORMATTING(91)
#define NYUSH_VTS_FOREGROUND_BRIGHT_GREEN __NYUSH_VTS_TEXT_FORMATTING(92)
#define NYUSH_VTS_FOREGROUND_BRIGHT_YELLOW __NYUSH_VTS_TEXT_FORMATTING(93)
#define NYUSH_VTS_FOREGROUND_BRIGHT_BLUE __NYUSH_VTS_TEXT_FORMATTING(94)
#define NYUSH_VTS_FOREGROUND_BRIGHT_MAGENTA __NYUSH_VTS_TEXT_FORMATTING(95)
#define NYUSH_VTS_FOREGROUND_BRIGHT_CYAN __NYUSH_VTS_TEXT_FORMATTING(96)
#define NYUSH_VTS_FOREGROUND_BRIGHT_WHITE __NYUSH_VTS_TEXT_FORMATTING(97)
#define NYUSH_VTS_FOREGROUND_DEFAULT __NYUSH_VTS_TEXT_FORMATTING(39)

#define NYUSH_VTS_BACKGROUND_BLACK __NYUSH_VTS_TEXT_FORMATTING(40)
#define NYUSH_VTS_BACKGROUND_RED __NYUSH_VTS_TEXT_FORMATTING(41)
#define NYUSH_VTS_BACKGROUND_GREEN __NYUSH_VTS_TEXT_FORMATTING(42)
#define NYUSH_VTS_BACKGROUND_YELLOW __NYUSH_VTS_TEXT_FORMATTING(43)
#define NYUSH_VTS_BACKGROUND_BLUE __NYUSH_VTS_TEXT_FORMATTING(44)
#define NYUSH_VTS_BACKGROUND_MAGENTA __NYUSH_VTS_TEXT_FORMATTING(45)
#define NYUSH_VTS_BACKGROUND_CYAN __NYUSH_VTS_TEXT_FORMATTING(46)
#define NYUSH_VTS_BACKGROUND_WHITE __NYUSH_VTS_TEXT_FORMATTING(47)
#define NYUSH_VTS_BACKGROUND_BRIGHT_BLACK __NYUSH_VTS_TEXT_FORMATTING(100)
#define NYUSH_VTS_BACKGROUND_BRIGHT_RED __NYUSH_VTS_TEXT_FORMATTING(101)
#define NYUSH_VTS_BACKGROUND_BRIGHT_GREEN __NYUSH_VTS_TEXT_FORMATTING(102)
#define NYUSH_VTS_BACKGROUND_BRIGHT_YELLOW __NYUSH_VTS_TEXT_FORMATTING(103)
#define NYUSH_VTS_BACKGROUND_BRIGHT_BLUE __NYUSH_VTS_TEXT_FORMATTING(104)
#define NYUSH_VTS_BACKGROUND_BRIGHT_MAGENTA __NYUSH_VTS_TEXT_FORMATTING(105)
#define NYUSH_VTS_BACKGROUND_BRIGHT_CYAN __NYUSH_VTS_TEXT_FORMATTING(106)
#define NYUSH_VTS_BACKGROUND_BRIGHT_WHITE __NYUSH_VTS_TEXT_FORMATTING(107)
#define NYUSH_VTS_BACKGROUND_DEFAULT __NYUSH_VTS_TEXT_FORMATTING(49)

#define NYUSH_VTS_FOREGROUND_RGB(R, G, B)                                      \
	__NYUSH_VTS_TEXT_FORMATTING(38; 2; R; G; B)
#define NYUSH_VTS_BACKGROUND_RGB(R, G, B)                                      \
	__NYUSH_VTS_TEXT_FORMATTING(48; 2; R; G; B)

#define NYUSH_VTS_CURSOR_HORIZONTAL_ABSOLUTE(VALUE)                            \
	NYUSH_VTS_ESCAPE "[" #VALUE "G"
#define NYUSH_VTS_CURSOR_BACKWARD(VALUE) NYUSH_VTS_ESCAPE "[" #VALUE "D"

#define NYUSH_VTS_SET_WINDOW_TITLE(TITLE) NYUSH_VTS_ESCAPE "]0;" TITLE "\x07"
